### ISSUE TITLE
Request for examples

### ISSUE THREAD

**Issue by vergissberlin** [infrablocks/concourse.js#1]
**Hi!**

Thank you very much for your efforts!
Could you please add examples to the README to get a better starting point?

kind regards,
André

**Comment by tobyclemson** [comment]
Hi André,

This library is still work in progress but if there's interest in using it, I can try and get a minimum viable version of it out this week.

The main piece remaining is to build an authenticated HTTP client that automatically creates and then refreshes the authentication token before expiry.

The client does not yet have full support for all API endpoints but there are some available.

In the meantime, you could try the [Fly.js](https://github.com/infrablocks/concourse.js/blob/master/src/Fly.js) version which was my first attempt. Example usage is in the [tests](https://github.com/infrablocks/concourse.js/blob/master/test/Fly.spec.js) and the interface follows that of the `fly` CLI. 

I'll document everything in the README once things are a bit more stable.

Thanks for you interest,
Toby

**Comment by tobyclemson** [comment]
Hi André,

The library is now in a usable state and the [README.md](README.md) contains usage instructions and examples.

Let me know if there's anything missing,
Thanks,
Toby

**Comment by tobyclemson** [comment]
Hi André,

I'm going to close this issue in a few days as I think it is resolved. Please let me know if you'd like to see anything more in the README.

Thanks,
Toby
