### ISSUE TITLE
The directory lib is no longer included into the published packages from the version 0.21.0 and up

### ISSUE THREAD

**Issue by rodgarci** [infrablocks/concourse.js#7]
Importing Client like below doesn't work anymore :

`import { Client } from '@infrablocks/concourse'`

**Comment by tobyclemson** [comment]
Hi Rodrigo,

Apologies, this was down to a missed build dependency in the new automated publishing process.

Version [0.25.0](https://www.npmjs.com/package/@infrablocks/concourse/v/0.25.0) reinstates the built `lib` directory in the package.

Thanks,
Toby
